### ISSUE TITLE
Doc comments cause failure

### ISSUE THREAD

**Issue by beamspease** [andersk/enum_primitive-rs#10] opened 2017-04-26 11:04 UTC
```
error: local ambiguity: multiple parsing options: built-in NTs ident ('variant') or 1 other option.
   --> src/dfu.rs:101:5
    |
101 |     /// No error condition is present.
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Sample code:
```
enum_from_primitive! {
#[repr(u8)]
pub enum DfuStatus {
    /// No error condition is present.
    Ok = 0x00,
}
}
```

**Comment by andersk** [comment] 2017-11-15 01:31
Duplicate of #2, which was fixed in Rust 1.20.

**Closed as completed by andersk** 2017-11-15 01:31 UTC
